GUILDBANK_LOADED_TEXT = "GuildBank Loaded. Use with /gbank or /guildbank";
GUILDBANK_INVENTORY_TEXT = "Inventory";
GUILDBANK_EQUIPMENT_TEXT = "Equipment";
GUILDBANK_BANK_TEXT = "Bank";
GUILDBANK_MONEY_TEXT = "Money";
GUILDBANK_TITLE_TEXT = "What do you want to post to your forum?";
GUILDBANK_STARTBUTTON_TEXT = "Start!";
GUILDBANK_HELP_TEXT = "Now just press CTRL-C to copy data to Clipboard.";
GUILDBANK_CLOSEBUTTON_TEXT = "Close";
GUILDBANK_WEBLINK_TEXT = "http://db.vanillagaming.org/?item=";