local L = AceLibrary("AceLocale-2.2"):new("guildbank")

L:RegisterTranslations("enUS", function() return {
  ["%s\n|cffFFA500Click:|r Show Export|r\n|cffFFA500Right-Click:|r Options"] = true,
  ["Bags"] = true,
  ["Bank"] = true,
  ["BBCode"] = true,
  ["Ctrl+C to copy, Ctrl+V on Forum. Esc to close"] = true,
  ["Disabling"] = true,
  ["Discord"] = true,
  ["Export Format"] = true,
  ["Export items to %s"] = true,  
  ["Export"] = true,
  ["Format"] = true,
  ["GuildBank"] = true,
  ["Hide minimap icon"] = true,
  ["Include Bags"] = true,
  ["Include Bank"] = true,
  ["Include Mail"] = true,
  ["Include Money"] = true,
  ["Item Patch"] = true,
  ["Link"] = true,
  ["Mail"] = true,
  ["Money"] = true,
  ["Online Database"] = true,
  ["Patch"] = true,
  ["|cffffbf00Warning|r > Export exceeds the Discord limit of 2000 characters."] = true,
} end)